### ISSUE TITLE
False positive detections from SMAC!

### ISSUE THREAD

**Issue by naydef** [50DKP/FF2-Official#350]
```
    Map: vsh_mini_city_v3 | Origin: 894 -1508 67 | Angles: 11 77 0 | Weapon:  | Team: 2 | Latency: 120ms
L 01/12/2016 - 18:57:53: [smac_cvars.smx | 0.8.6.0] Assassin Spy Greed (ID: STEAM_0:1:149137969 | IP: 212.25.57.240) was banned for failing checks on convar "host_timescale". result "Okay" | CompType: "replicated" | cvarValue "1" | value: "1.000000" | value2: ""
    Map: vsh_mini_city_v3 | Origin: 894 -1508 67 | Angles: 10 76 0 | Weapon:  | Team: 3 | Latency: 53ms
L 01/12/2016 - 18:58:21: [smac_cvars.smx | 0.8.6.0] pepiwe (ID: STEAM_0:0:150750459 | IP: 84.252.56.96) was banned for failing checks on convar "host_timescale". result "Okay" | CompType: "replicated" | cvarValue "1" | value: "1.000000" | value2: ""
    Map: vsh_mini_city_v3 | Origin: 894 -1508 67 | Angles: 10 76 0 | Weapon:  | Team: 0 | Latency: 62ms
L 01/12/2016 - 19:01:11: [smac_cvars.smx | 0.8.6.0] berke.abi (ID: STEAM_0:0:153911996 | IP: 176.43.145.48) was banned for failing checks on convar "host_timescale". result "Okay" | CompType: "replicated" | cvarValue "1" | value: "1.000000" | value2: ""
    Map: vsh_mini_city_v3 | Origin: 894 -1508 67 | Angles: 10 76 0 | Weapon:  | Team: 0 | Latency: 103ms
L 01/12/2016 - 19:07:06: [smac_cvars.smx | 0.8.6.0] Hurkancs (ID: STEAM_0:1:118697765 | IP: 83.166.221.52) was banned for failing checks on convar "host_timescale". result "Okay" | CompType: "replicated" | cvarValue "1" | value: "1.000000" | value2: ""
    Map: vsh_mini_city_v3 | Origin: 894 -1508 67 | Angles: 10 76 0 | Weapon:  | Team: 0 | Latency: 61ms
L 01/12/2016 - 19:07:50: [smac_cvars.smx | 0.8.6.0] ola.buli (ID: STEAM_0:0:120451717 | IP: 89.229.165.52) was banned for failing checks on convar "host_timescale". result "Okay" | CompType: "replicated" | cvarValue "1" | value: "1.000000" | value2: ""
    Map: vsh_mini_city_v3 | Origin: 894 -1508 67 | Angles: 10 76 0 | Weapon:  | Team: 0 | Latency: 127ms
```

This thing is happening sometimes and it's boring to unban all players. Of course I run Freak Fortress 2 and I know that the plugin removes "host_timescale" and "sv_cheats" for detection, but the strangest thing is that 1.000000 and 1 is not equal for SMAC. So where I have to go for support?

**Comment by naydef** [comment]
Same happened again on my own server, maybe I will go to ask in the SMAC thread!

**Comment by shadow93** [comment]
This has been happening to my server as well lately.

**Comment by 50Wliu** [comment]
Fantastic.  Is this a SMAC bug or something FF2 needs to work around?

**Comment by 50Wliu** [comment]
I don't think this is FF2's fault.  SMAC should be checking the server-wide value first before banning players for their value.  I might be able to work around it by using `SetConVarInt` instead of `SetConVarFloat`, but I'd rather SMAC fix it.

**Comment by naydef** [comment]
This is both FF2 and SMAC fail. The ff2 fault is that the FileExits check make script timeouts prevent the execution of the commands that remove these cvars from checking. The smac fault is that the plugin compares float values using StrEqual. (1.0==1.00000) is true, but StrEqual("1.0", "1.0000000") is not true. This is the error message, but it's from shadow's ff2 fork:
```
L 01/20/2016 - 21:48:21: [SM] Plugin encountered error 30: Script execution timed out
L 01/20/2016 - 21:48:21: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 01/20/2016 - 21:48:21: [SM]   [0]  Line 3039, L:\scripting\freak_fortress_2_1.40.sp::LoadCharacter()
L 01/20/2016 - 21:48:21: [SM]   [1]  Line 2878, L:\scripting\freak_fortress_2_1.40.sp::FindCharacters()
L 01/20/2016 - 21:48:21: [SM]   [2]  Line 2671, L:\scripting\freak_fortress_2_1.40.sp::EnableFF2()
L 01/20/2016 - 21:48:21: [SM]   [3]  Line 2509, L:\scripting\freak_fortress_2_1.40.sp::OnConfigsExecuted()
```

If there is something that can be done, maybe a cvar to specify if the files existence will be checked.

**Comment by naydef** [comment]
Another thing I have noticed is during the Ninja spy slow-motion rage, I'm experiencing prediction errors(weapons are clientside-predicted) which can be due to smac_speedhack plugin. The plugin prevents speedhacks(client think that the server's host_timescale is 0.5 but the real value is 1.0. So the clients maybe sends less/more packages over the network)

**Comment by WildCard65** [comment]
@50Wliu SMAC only checks the CVAR values on replicated cvars with value it grabbed from the server side one at time CVAR was added to it's watch list.

**Comment by naydef** [comment]
Cvars like ```host_timescale``` and ```sv_cheats``` are by default in the SMAC check list. The problem here is that before the actual commands for removing these cvars are called, FF2 checks if the boss files are on the server using ```FileExist()``` check. But this function needs time to check all the files. For this reason, the Sourcemod Watchdog stop execution of the script and all the code after this checks. This is now fixed. Just set the watchdog time higher value. The second problem is these clien-side zeroes, which are not equal to the server-side value. And SMAC checks replicated cvars, using StrEqual().

**Comment by naydef** [comment]
I have idead. Instead of setting back to constant value, let's force cvar replication!

**Comment by WildCard65** [comment]
@naydef Still won't work as the cvar value SMAC checks replicated cvars against is the value cached by SMAC at time CVAR was added to internal watch list.

**Comment by naydef** [comment]
```sourcemod
new Handle:cvar=FindCvar("host_timescale");
SetConVarFloat(cvar, GetConVarFloat(cvar), true);
```

**Comment by WildCard65** [comment]
@naydef Again, STILL WON'T WORK!
```
bool:AddCvar(CvarOrder:COrder, String:sCvar[], CvarComp:CCompType, CvarAction:CAction, const String:sValue[] = "", const String:sValue2[] = "")
{
	if (CCompType == Comp_Invalid || CAction == Action_Invalid)
		return false;
	
	// Trie is case sensitive.
	StringToLower(sCvar);
	
	decl String:sNewValue[MAX_CVAR_VALUE_LEN], Handle:hCvar;
	
	if (CCompType == Comp_Replicated)
	{
		hCvar = FindConVar(sCvar);
		
		if (hCvar == INVALID_HANDLE || !(GetConVarFlags(hCvar) & FCVAR_REPLICATED))
			return false;
			
		GetConVarString(hCvar, sNewValue, sizeof(sNewValue));
	}
	else
	{
		strcopy(sNewValue, sizeof(sNewValue), sValue);
	}
	
	decl Handle:hDataTrie;
	
	if (GetTrieValue(g_hCvarTrie, sCvar, hDataTrie))
	{
		//SetTrieValue(hDataTrie, Cvar_Order, COrder);
		SetTrieString(hDataTrie, Cvar_Name, sCvar);
		SetTrieValue(hDataTrie, Cvar_CompType, CCompType);
		SetTrieValue(hDataTrie, Cvar_Action, CAction);
		SetTrieString(hDataTrie, Cvar_Value, sNewValue);
		SetTrieString(hDataTrie, Cvar_Value2, sValue2);
		//SetTrieValue(hDataTrie, Cvar_ReplicatedTime, 0);
	}
	else
	{
		// Setup cvar data
		hDataTrie = CreateTrie();
		
		SetTrieValue(hDataTrie, Cvar_Order, COrder);
		SetTrieString(hDataTrie, Cvar_Name, sCvar);
		SetTrieValue(hDataTrie, Cvar_CompType, CCompType);
		SetTrieValue(hDataTrie, Cvar_Action, CAction);
		SetTrieString(hDataTrie, Cvar_Value, sNewValue);
		SetTrieString(hDataTrie, Cvar_Value2, sValue2);
		SetTrieValue(hDataTrie, Cvar_ReplicatedTime, 0);
		
		// Add cvar to lists
		SetTrieValue(g_hCvarTrie, sCvar, hDataTrie);
		PushArrayCell(g_hCvarADT, hDataTrie);
		g_iADTSize = GetArraySize(g_hCvarADT);
		
		// Begin replication
		if (CCompType == Comp_Replicated)
		{
			HookConVarChange(hCvar, OnConVarChanged);
			ReplicateToAll(hCvar, sNewValue);
		}
		
		// Scramble
		if (g_bPluginStarted)
		{
			ScrambleCvars();
		}
	}
	
	return true;
}
```

**Comment by WildCard65** [comment]
@naydef After looking careful more through smac's cvar source, seems like it'll update the replication value it checks if it changes server side.

**Comment by naydef** [comment]
Insanely old...
